#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"
#include "math.h"

#include "sdkconfig.h" // generated by "make menuconfig"
#include "ssd1306.h"
#include "mcp3008.h"
#include "ds18b20.h"

#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define SDA_PIN GPIO_NUM_21
#define SCL_PIN GPIO_NUM_22
#define I2C_FREQUENCY 100000
#define VCC_ADC 5000.0
#define TEMP_BUS 25
#define OLED_RESET 4

Adafruit_SSD1306 display(OLED_RESET);


double calc_temperature(DeviceAddress *temp_sensors) {
	float temp = ds18b20_get_temp();
    ESP_LOGI("TEMPERATURE", "%.2f°C", temp);

    return (double) temp;
}

double calc_pH(MCP3008 *device){
    double ph, voltage;
    float calibration_factor = 21.34;

    mcp3008_read(device, 1);

    voltage = ((float) device->data / (float)(1<<device->bits)) * VCC_ADC;
    ph = -5.70 * (voltage/1000) + calibration_factor;

    ESP_LOGI("PH", "PH: %.2f, Voltage: %.2fmV, data: %d", ph, voltage, device->data);
    return ph;
}

double calc_turbidez(MCP3008 *device){
    double voltage, ntu;

    mcp3008_read(device, 0);
    voltage = ((float) device->data / (float)(1 << device->bits)) * VCC_ADC;

    if ( voltage < 2500 ) {
        ntu = 3000;
    }
    else if (voltage > 4200) {
        ntu = 0;
    }
    else {
        ntu = -1120.4 * pow(voltage/1000, 2) + 5742.3 * (voltage/1000) - 4352.8;
    }

    ESP_LOGI("TURBIDEZ", "NTU: %.2f, Voltage: %.2fmV, data: %d", ntu, voltage, device->data);
    return ntu;
}

void show_data(double turbidez,double ph, double temperature){
    display.setCursor(0,2);
    display.print("Temp: %2.f C", temperature);

    display.setCursor(0,12);
    display.print("PH: %2.f", ph); //7.01

    display.setCursor(0,22);
    display.print("NTU: %.f", turbidez); // 503
  
}

void set_display(){
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);  //Inicializa OLED com endereço I2C 0x3C (para 128x64)
  display.clearDisplay();
  display.display();
  display.setTextSize(.5);
  display.setTextColor(WHITE);

}

void app_main(void){
    DeviceAddress temp_sensors[MAX_DEVICE_BUS];
    MCP3008 device;
    mcp3008_init(&device, GPIO_NUM_12, GPIO_NUM_13, GPIO_NUM_14, GPIO_NUM_26);

    ssd1306_init(SDA_PIN, SCL_PIN, I2C_FREQUENCY);

    ds18b20_init(TEMP_BUS);
	ds18b20_get_address(temp_sensors);
	ds18b20_setResolution(temp_sensors, 2, 10);

    set_display()

    while (1)
    {   
        // calcula a turbidez da agua
        turbidez = calc_turbidez(&device);
        ph = calc_pH(&device);
        temperature = calc_temperature(temp_sensors);
        show_data(turbidez, ph, temperature)
        vTaskDelay(1500/portTICK_PERIOD_MS);
    }
}