#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"
#include "math.h"

#include "sdkconfig.h" // generated by "make menuconfig"
#include "ssd1306.h"
#include "mcp3008.h"

#define SDA_PIN GPIO_NUM_21
#define SCL_PIN GPIO_NUM_22
#define I2C_FREQUENCY 100000

void app_main(void){

    MCP3008 device;
    mcp3008_init(&device, GPIO_NUM_12, GPIO_NUM_13, GPIO_NUM_14, GPIO_NUM_26);
    ssd1306_init(SDA_PIN, SCL_PIN, I2C_FREQUENCY);

    while (1)
    {   
        // calcula a turbidez da agua
        // calc_turbidez(&device);
        vTaskDelay(1500/portTICK_PERIOD_MS);
    }
}